SUB_LINK = 'https://buy.stripe.com/test_bIY14r79x1j9bhmfYY'
api_key = 'sk_test_51Qpy3QBzR0k5QTwf2SusO80Z8pJ31ZdukDjBlZuUHsJigAQR2iOcrF8wFIQMOv73V4JwJYc0DqluxlHMNdWgYqkd00byyfxfwG'
testing_mode = true 
